### ISSUE TITLE
Unable to Connect to MongoDB Database with Custom Configuration

### ISSUE THREAD

**Issue by timothyjoseph263** [nia-cloud-official/zora_framework#1]
Description: I'm experiencing issues when trying to connect to a MongoDB database using a custom configuration in the Zora Database Testing Framework. I've followed the installation and configuration steps outlined in the documentation, but I'm still unable to establish a connection.

Steps to Reproduce:

    Clone the Zora Database Testing Framework repository: git clone https://github.com/your-username/zora-database-testing.git
    Configure the config/database.php file with the following custom MongoDB settings:

php

'mongodb' => [

    'custom' => [

        'host' => 'my-mongodb-host',

        'username' => 'my-mongodb-username',

        'password' => 'my-mongodb-password',

        'database' => 'my-mongodb-database'

    ]

]

    Run the tests using the following PHP script:

php

use Zora\Framework\Zora;

$dbType = 'mongodb';

$zora = new Zora($dbType);

$result = $zora->runTests();

echo json_encode([

    'message' => $result['message'],

    'report' => $result['report']

]);

Expected Result: The tests should run successfully and provide a detailed report on the test results.

Actual Result: The connection to the MongoDB database fails, and the tests do not run.

Additional Information: I've double-checked my MongoDB credentials and ensured that the database is running. I've also tried using the default MongoDB configuration, but the issue persists.

**Comment by nia-cloud-official** [comment]
Thank you for reporting this issue. Let's troubleshoot the problem to find a solution.

**Steps to Verify Configuration:**

1. **Check MongoDB Connection:**
   Ensure that you can connect to your MongoDB instance outside of the Zora framework using the same credentials. You can use a MongoDB client or a simple script to verify the connection:
   
   ```php
   try {
       $manager = new MongoDB\Driver\Manager('mongodb://my-mongodb-username:my-mongodb-password@my-mongodb-host/my-mongodb-database');
       echo "Connection successful!";
   } catch (MongoDB\Driver\Exception\Exception $e) {
       echo "Connection failed: " . $e->getMessage();
   }
   ```

2. **Verify Configuration in Zora:**
   Ensure that the `config/database.php` file is correctly configured. The configuration should look like this:
   
   ```php
   return [
       'mongodb' => [
           'custom' => [
               'host' => 'my-mongodb-host',
               'username' => 'my-mongodb-username',
               'password' => 'my-mongodb-password',
               'database' => 'my-mongodb-database'
           ]
       ]
   ];
   ```

3. **Review Zora Configuration Loading:**
   Check if Zora is correctly loading the MongoDB configuration. Add debug statements in the `Zora` class to print the configuration it uses:
   
   ```php
   $config = include('config/database.php');
   print_r($config['mongodb']['custom']);
   ```

4. **Ensure MongoDB Extension is Enabled:**
   Verify that the MongoDB PHP extension is installed and enabled. You can check this with the following command:
   
   ```sh
   php -m | grep mongodb
   ```

5. **Error Details:**
   If the connection fails, there should be error messages or exceptions. Ensure you catch and log these exceptions to understand why the connection fails. Update your test script to capture these details:
   
   ```php
   use Zora\Framework\Zora;
   
   $dbType = 'mongodb';
   $zora = new Zora($dbType);
   
   try {
       $result = $zora->runTests();
       echo json_encode([
           'message' => $result['message'],
           'report' => $result['report']
       ]);
   } catch (Exception $e) {
       echo json_encode([
           'error' => $e->getMessage()
       ]);
   }
   ```

Please try the above steps and let us know if you still encounter issues. Providing any error messages or logs will help us diagnose the problem more effectively.

Thank you for your cooperation!
